### ISSUE TITLE
Main domain is  not getting updated in Sepolia 

### ISSUE THREAD

**Issue by revengexd** [starknet-id/app.starknet.id#739]
https://github.com/starknet-id/app.starknet.id/assets/55296770/9c21c9e8-bd8a-4daa-a60a-530ee2bc35ae

As you can see VINTAGE.STARK is the main domain but it's not showing over the profile !

**Comment by irisdv** [comment]
This is due the a change in the naming contract to the `address_to_domain` function (only deployed on sepolia right now). It will be fixed by : https://github.com/starknet-id/starknetid.js/pull/32
We will just have to update the package version in the app once this PR has been reviewed and deployed.

**Comment by fricoben** [comment]
Seems good then
